/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DaruratRouteImport } from './routes/darurat'
import { Route as PanduanRouteImport } from './routes/panduan'
import { Route as SiagaRouteImport } from './routes/siaga'
import { Route as BencanaSlugRouteImport } from './routes/bencana.$slug'
import { Route as PertolonganSlugRouteImport } from './routes/pertolongan.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DaruratRoute = DaruratRouteImport.update({
  id: '/darurat',
  path: '/darurat',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanRoute = PanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const SiagaRoute = SiagaRouteImport.update({
  id: '/siaga',
  path: '/siaga',
  getParentRoute: () => rootRouteImport,
} as any)
const BencanaSlugRoute = BencanaSlugRouteImport.update({
  id: '/bencana/$slug',
  path: '/bencana/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PertolonganSlugRoute = PertolonganSlugRouteImport.update({
  id: '/pertolongan/$slug',
  path: '/pertolongan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/darurat': typeof DaruratRoute
  '/panduan': typeof PanduanRoute
  '/siaga': typeof SiagaRoute
  '/bencana/$slug': typeof BencanaSlugRoute
  '/pertolongan/$slug': typeof PertolonganSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/darurat': typeof DaruratRoute
  '/panduan': typeof PanduanRoute
  '/siaga': typeof SiagaRoute
  '/bencana/$slug': typeof BencanaSlugRoute
  '/pertolongan/$slug': typeof PertolonganSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/darurat': typeof DaruratRoute
  '/panduan': typeof PanduanRoute
  '/siaga': typeof SiagaRoute
  '/bencana/$slug': typeof BencanaSlugRoute
  '/pertolongan/$slug': typeof PertolonganSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/darurat'
    | '/panduan'
    | '/siaga'
    | '/bencana/$slug'
    | '/pertolongan/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/darurat'
    | '/panduan'
    | '/siaga'
    | '/bencana/$slug'
    | '/pertolongan/$slug'
  id:
    | '__root__'
    | '/'
    | '/darurat'
    | '/panduan'
    | '/siaga'
    | '/bencana/$slug'
    | '/pertolongan/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaruratRoute: typeof DaruratRoute
  PanduanRoute: typeof PanduanRoute
  SiagaRoute: typeof SiagaRoute
  BencanaSlugRoute: typeof BencanaSlugRoute
  PertolonganSlugRoute: typeof PertolonganSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darurat': {
      id: '/darurat'
      path: '/darurat'
      fullPath: '/darurat'
      preLoaderRoute: typeof DaruratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan': {
      id: '/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof PanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siaga': {
      id: '/siaga'
      path: '/siaga'
      fullPath: '/siaga'
      preLoaderRoute: typeof SiagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bencana/$slug': {
      id: '/bencana/$slug'
      path: '/bencana/$slug'
      fullPath: '/bencana/$slug'
      preLoaderRoute: typeof BencanaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pertolongan/$slug': {
      id: '/pertolongan/$slug'
      path: '/pertolongan/$slug'
      fullPath: '/pertolongan/$slug'
      preLoaderRoute: typeof PertolonganSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaruratRoute: DaruratRoute,
  PanduanRoute: PanduanRoute,
  SiagaRoute: SiagaRoute,
  BencanaSlugRoute: BencanaSlugRoute,
  PertolonganSlugRoute: PertolonganSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
